{% set name = "deptry" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deptry-{{ version }}.tar.gz
  sha256: 9cf8e398ea394f90ccfa8e11d7dcfba8ed485f6a33270ee2b024475b72a00d11

build:
  skip: true  # [py<38]
  entry_points:
    - deptry = deptry.cli:deptry
    # Setting CARGO_HOME is a workaround for "path too long" error on
    # Windows due to the 260 character limit for paths, and because the
    # ruff repo (which is a dependency) has some files with very long names.
    # Ref: <https://github.com/conda-forge/deptry-feedstock/issues/5>
  script: |
    set "CARGO_HOME=C:\cargo"
    echo "building..."
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.5,<2.0                     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.5,<2.0
    - pip
  run:
    - python
    - click >=8.0.0,<9
    - colorama >=0.4.6  # [win]
    - tomli >=2.0.1  # [py<311]

test:
  imports:
    - deptry
  commands:
    - pip check
    - deptry --help
  requires:
    - pip

about:
  home: https://deptry.com/
  dev_url: https://github.com/fpgmaas/deptry
  doc_url: https://deptry.com/
  summary: A command line utility to check for unused, missing and transitive dependencies in a Python project.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - maresb
    - fpgmaas
